export const DesktopChannels = {
  loadTheme: "hydracode:load-theme",
  setBundledTheme: "hydracode:set-bundled-theme",
  selectProject: "hydracode:select-project",
  listProjects: "hydracode:list-projects",
  openProject: "hydracode:open-project",
  closeProject: "hydracode:close-project",
  projectUpdate: "hydracode:project-update",
  selectSession: "hydracode:select-session",
  createSession: "hydracode:create-session",
  submitPrompt: "hydracode:submit-prompt",
  interrupt: "hydracode:interrupt",
  listSavedLayouts: "hydracode:list-saved-layouts",
  saveLayout: "hydracode:save-layout",
  layoutSave: "hydracode:layout-save",
  paneFocus: "hydracode:pane-focus",
  paneSplit: "hydracode:pane-split",
  paneClose: "hydracode:pane-close",
  promptFocus: "hydracode:prompt-focus",
  followLatest: "hydracode:follow-latest",
  updateSubscribe: "hydracode:update-subscribe",
  updateState: "hydracode:update-state",
  updateCheck: "hydracode:update-check",
  updateInstall: "hydracode:update-install",
} as const
