export const DesktopChannels = {
  loadTheme: "hydracode:load-theme",
  selectProject: "hydracode:select-project",
  listProjects: "hydracode:list-projects",
  openProject: "hydracode:open-project",
  closeProject: "hydracode:close-project",
  projectUpdate: "hydracode:project-update",
  selectSession: "hydracode:select-session",
  createSession: "hydracode:create-session",
  submitPrompt: "hydracode:submit-prompt",
  interrupt: "hydracode:interrupt",
  updateSubscribe: "hydracode:update-subscribe",
  updateState: "hydracode:update-state",
  updateCheck: "hydracode:update-check",
  updateInstall: "hydracode:update-install",
} as const
